export enum BOOK_GENRE {
  CRIME = 'crime',
  SCIENCE_FICTION = 'science_fiction',
  POST_APOCALYPTICK = 'post_apocalyptic',
  DISTOPIA = 'distopia',
  FANTASY = 'fantasy',
  ROMANTIC = 'romantic',
  WESTERN = 'western',
  HORROR = 'horror',
  CLASSIC = 'classic',
  FAIRY_TAIL = 'fairy_tail',
  FAN_FICTION = 'fan_fiction',
  HISTORY = 'history',
  HUMOR = 'humor',
  BIOGRAPHY = 'biograpy',
  JOURNALISM = 'journalism',
  PHILOSOPHY = 'philosophy',
  RELIGION = 'religion',
  TEXT_BOOK = 'text_book',
  SCIENCE = 'science',
  ENCYCLOPEDIA = 'encyclopedia',
  TECH = 'technical_writing',
  COOK = 'cook_book'
}
